#!/usr/bin/env python3

import argparse
import math
from pathlib import Path

import cv2
import numpy as np


DEFAULT_DICT_SIZE = 57961
DEFAULT_MARKER_BITS = 6
DEFAULT_CACHE_DIR = Path(".")


def parse_args():
    parser = argparse.ArgumentParser(description="Windows receiver: detect ArUco tags and pose.")
    parser.add_argument(
        "--dict-size",
        type=int,
        default=DEFAULT_DICT_SIZE,
        help="Number of IDs in the dictionary. Must match the NUC sender.",
    )
    parser.add_argument("--marker-bits", type=int, default=DEFAULT_MARKER_BITS)
    parser.add_argument("--cache-dir", type=Path, default=DEFAULT_CACHE_DIR)
    parser.add_argument(
        "--marker-size-m",
        type=float,
        required=True,
        help="Real displayed marker black-square side length in meters.",
    )
    parser.add_argument("--camera", type=int, default=0)
    parser.add_argument("--width", type=int, default=1280)
    parser.add_argument("--height", type=int, default=800)
    parser.add_argument("--fps", type=int, default=60)
    parser.add_argument("--fx", type=float, default=956.80819)
    parser.add_argument("--fy", type=float, default=956.46353)
    parser.add_argument("--cx", type=float, default=653.72184)
    parser.add_argument("--cy", type=float, default=358.43826)
    parser.add_argument("--k1", type=float, default=-0.005408)
    parser.add_argument("--k2", type=float, default=0.029448)
    parser.add_argument("--p1", type=float, default=-0.000804)
    parser.add_argument("--p2", type=float, default=-0.00107)
    parser.add_argument("--k3", type=float, default=0.0)
    return parser.parse_args()


def cache_path(cache_dir, dict_size, marker_bits):
    return cache_dir / f"aruco_custom_{marker_bits}x{marker_bits}_{dict_size}.npz"


def load_dictionary(path):
    data = np.load(path)
    dictionary = cv2.aruco.Dictionary()
    dictionary.bytesList = data["bytesList"]
    dictionary.markerSize = int(data["markerSize"])
    dictionary.maxCorrectionBits = int(data["maxCorrectionBits"])
    return dictionary


def require_dictionary(dict_size, marker_bits, cache_dir):
    path = cache_path(cache_dir, dict_size, marker_bits)
    if not path.exists():
        raise FileNotFoundError(
            f"Dictionary cache not found: {path}\n"
            "Copy the .npz file generated by aruco_screen_sender.py into this folder."
        )
    print(f"Loading dictionary cache: {path}", flush=True)
    return load_dictionary(path), path


def make_camera_matrix(fx, fy, cx, cy):
    return np.array(
        [
            [fx, 0.0, cx],
            [0.0, fy, cy],
            [0.0, 0.0, 1.0],
        ],
        dtype=np.float64,
    )


def make_dist_coeffs(k1, k2, p1, p2, k3):
    return np.array([k1, k2, p1, p2, k3], dtype=np.float64)


def make_object_points(marker_size_m):
    half = marker_size_m * 0.5
    return np.array(
        [
            [-half, half, 0.0],
            [half, half, 0.0],
            [half, -half, 0.0],
            [-half, -half, 0.0],
        ],
        dtype=np.float32,
    )


def open_camera(index, width, height, fps):
    cap = cv2.VideoCapture(index)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open camera index {index}.")
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, float(width))
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, float(height))
    cap.set(cv2.CAP_PROP_FPS, float(fps))
    cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)
    return cap


def yaw_from_rvec(rvec):
    rotation, _ = cv2.Rodrigues(rvec)
    return math.degrees(math.atan2(rotation[1, 0], rotation[0, 0]))


def main():
    args = parse_args()
    if args.marker_size_m <= 0.0:
        raise ValueError("--marker-size-m must be positive.")

    dictionary, dict_path = require_dictionary(args.dict_size, args.marker_bits, args.cache_dir)
    print(f"Using dictionary: {dict_path}", flush=True)

    detector = cv2.aruco.ArucoDetector(dictionary, cv2.aruco.DetectorParameters())
    camera_matrix = make_camera_matrix(args.fx, args.fy, args.cx, args.cy)
    dist_coeffs = make_dist_coeffs(args.k1, args.k2, args.p1, args.p2, args.k3)
    object_points = make_object_points(args.marker_size_m)

    cap = open_camera(args.camera, args.width, args.height, args.fps)
    cv2.namedWindow("aruco receiver", cv2.WINDOW_NORMAL)
    last_print = None

    try:
        while True:
            ok, frame = cap.read()
            if not ok:
                print("Camera frame read failed.", flush=True)
                break

            corners, ids, rejected = detector.detectMarkers(frame)
            if ids is not None and len(ids) > 0:
                cv2.aruco.drawDetectedMarkers(frame, corners, ids)
                for marker_corners, detected_id_array in zip(corners, ids):
                    detected_id = int(detected_id_array[0])
                    image_points = marker_corners.reshape(4, 2).astype("float32")
                    solved, rvec, tvec = cv2.solvePnP(
                        object_points,
                        image_points,
                        camera_matrix,
                        dist_coeffs,
                        flags=cv2.SOLVEPNP_IPPE_SQUARE,
                    )
                    if not solved:
                        continue

                    cv2.drawFrameAxes(
                        frame,
                        camera_matrix,
                        dist_coeffs,
                        rvec,
                        tvec,
                        args.marker_size_m * 0.5,
                    )
                    center = image_points.mean(axis=0)
                    x, y, z = tvec.reshape(3)
                    yaw_deg = yaw_from_rvec(rvec)
                    text = (
                        f"id={detected_id} "
                        f"x={x:.3f}m y={y:.3f}m z={z:.3f}m yaw={yaw_deg:.1f}deg"
                    )
                    cv2.putText(
                        frame,
                        text,
                        (20, 40),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.75,
                        (0, 255, 0),
                        2,
                        cv2.LINE_AA,
                    )

                    rounded = (
                        detected_id,
                        round(float(center[0]), 1),
                        round(float(center[1]), 1),
                        round(float(x), 3),
                        round(float(y), 3),
                        round(float(z), 3),
                        round(float(yaw_deg), 1),
                    )
                    if rounded != last_print:
                        print(
                            f"detected_id={detected_id} "
                            f"center=({center[0]:.1f},{center[1]:.1f}) "
                            f"tvec_m=({x:.3f},{y:.3f},{z:.3f}) "
                            f"yaw_deg={yaw_deg:.1f}",
                            flush=True,
                        )
                        last_print = rounded

            cv2.imshow("aruco receiver", frame)
            key = cv2.waitKey(1) & 0xFF
            if key in (27, ord("q")):
                break
    finally:
        cap.release()
        cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
