# Goal
bool task_complete   # ->1
float32 target_dist  
---
# Result
bool success          
---
# Feedback(TX 0x02): 
float32 x_error       # 机械臂坐标系 X 轴偏差
float32 y_error       # Y 轴偏差
float32 z_error       # Z轴偏差
